<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shop</name>
   <tag></tag>
   <elementGuidId>2d0fcb5d-9afe-4d00-a0a1-063b7455a9aa</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;sprint-fonts-loaded&quot;]/body[@class=&quot;vanilla-modal&quot;]/div[@class=&quot;sprint-app&quot;]/header[@class=&quot;layout-header&quot;]/div[2]/div[@class=&quot;sprint-header-bottom&quot;]/div[@class=&quot;sprint-header-inner&quot;]/div[@class=&quot;sprint-header-meta&quot;]/nav[@class=&quot;sprint-header-nav hide-with-overlay&quot;]/ul[@class=&quot;sprint-menu&quot;]/li[3]/a[@class=&quot;sprint-menu__root js-nav-link-root&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
