<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Checkout</name>
   <tag></tag>
   <elementGuidId>f9a0b534-c678-48a9-b5d9-1b35318e3739</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--sm button--full font-medium</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Checkout
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;omni-cart-aside&quot;)/sprint-cart-app[@class=&quot;omni-theme-aside&quot;]/sprint-cart-omni[1]/div[@class=&quot;cart-omni cart-omni--loaded&quot;]/div[@class=&quot;cart-omni-inner&quot;]/div[@class=&quot;cart-omni-body&quot;]/div[1]/footer[@class=&quot;cart-omni-footer bgc--gray-dark align-center&quot;]/sprint-cart-checkout-button[1]/button[@class=&quot;button button--sm button--full font-medium&quot;]</value>
   </webElementProperties>
</WebElementEntity>
