<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_device-tile__img</name>
   <tag></tag>
   <elementGuidId>97499e95-6b2d-4d83-8ae5-c8926152d85b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/sprint/commerce/devices/samsung/samsung_galaxy_s9_plus/midnight_black/devicenb_650x900.png/_jcr_content/renditions/cq5dam.thumbnail.220.220.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>device-tile__img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Samsung Galaxy S9+</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>if (this.src.indexOf('') === -1) this.src=''</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-device-type-indicator&quot;)/li[@class=&quot;col-xs-24 col-sm-12 col-lg-8 text-center device-tile&quot;]/a[@class=&quot;device-tile__link&quot;]/div[@class=&quot;device-tile__img-wrap&quot;]/img[@class=&quot;device-tile__img&quot;]</value>
   </webElementProperties>
</WebElementEntity>
